// Generated by purs version 0.15.16
import * as Control_Comonad from "../Control.Comonad/index.js";
import * as Control_Comonad_Env_Trans from "../Control.Comonad.Env.Trans/index.js";
import * as Control_Comonad_Store_Trans from "../Control.Comonad.Store.Trans/index.js";
import * as Control_Comonad_Traced_Trans from "../Control.Comonad.Traced.Trans/index.js";
import * as Control_Comonad_Trans_Class from "../Control.Comonad.Trans.Class/index.js";
import * as Control_Extend from "../Control.Extend/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
var lower = /* #__PURE__ */ Control_Comonad_Trans_Class.lower(Control_Comonad_Env_Trans.comonadTransEnvT);
var pos = function (dict) {
    return dict.pos;
};
var peek = function (dict) {
    return dict.peek;
};
var peeks = function (dictComonadStore) {
    return function (f) {
        return function (x) {
            return peek(dictComonadStore)(Data_Function.apply(f)(pos(dictComonadStore)(x)))(x);
        };
    };
};
var seeks = function (dictComonadStore) {
    var duplicate = Control_Extend.duplicate((dictComonadStore.Comonad0()).Extend0());
    return function (f) {
        var $42 = peeks(dictComonadStore)(f);
        return function ($43) {
            return $42(duplicate($43));
        };
    };
};
var seek = function (dictComonadStore) {
    var duplicate = Control_Extend.duplicate((dictComonadStore.Comonad0()).Extend0());
    return function (s) {
        var $44 = peek(dictComonadStore)(s);
        return function ($45) {
            return $44(duplicate($45));
        };
    };
};
var experiment = function (dictComonadStore) {
    var peek1 = peek(dictComonadStore);
    return function (dictFunctor) {
        return function (f) {
            return function (x) {
                return Data_Functor.map(dictFunctor)(Data_Function.flip(peek1)(x))(f(pos(dictComonadStore)(x)));
            };
        };
    };
};
var comonadStoreTracedT = function (dictComonadStore) {
    var pos1 = pos(dictComonadStore);
    var Comonad0 = dictComonadStore.Comonad0();
    var comonadTracedT = Control_Comonad_Traced_Trans.comonadTracedT(Comonad0);
    return function (dictMonoid) {
        var lower1 = Control_Comonad_Trans_Class.lower(Control_Comonad_Traced_Trans.comonadTransTracedT(dictMonoid));
        var lower2 = lower1(Comonad0);
        var comonadTracedT1 = comonadTracedT(dictMonoid);
        return {
            pos: (function () {
                var $46 = lower1(Comonad0);
                return function ($47) {
                    return pos1($46($47));
                };
            })(),
            peek: function (s) {
                var $48 = peek(dictComonadStore)(s);
                return function ($49) {
                    return $48(lower2($49));
                };
            },
            Comonad0: function () {
                return comonadTracedT1;
            }
        };
    };
};
var comonadStoreStoreT = function (dictComonad) {
    var comonadStoreT = Control_Comonad_Store_Trans.comonadStoreT(dictComonad);
    return {
        pos: function (v) {
            return v.value1;
        },
        peek: function (s) {
            return function (v) {
                return Control_Comonad.extract(dictComonad)(v.value0)(s);
            };
        },
        Comonad0: function () {
            return comonadStoreT;
        }
    };
};
var comonadStoreEnvT = function (dictComonadStore) {
    var Comonad0 = dictComonadStore.Comonad0();
    var lower1 = lower(Comonad0);
    var comonadEnvT = Control_Comonad_Env_Trans.comonadEnvT(Comonad0);
    return {
        pos: (function () {
            var $50 = pos(dictComonadStore);
            var $51 = lower(Comonad0);
            return function ($52) {
                return $50($51($52));
            };
        })(),
        peek: function (s) {
            var $53 = peek(dictComonadStore)(s);
            return function ($54) {
                return $53(lower1($54));
            };
        },
        Comonad0: function () {
            return comonadEnvT;
        }
    };
};
export {
    peek,
    pos,
    experiment,
    peeks,
    seek,
    seeks,
    comonadStoreStoreT,
    comonadStoreEnvT,
    comonadStoreTracedT
};
//# sourceMappingURL=index.js.map
