// Generated by purs version 0.15.16
import * as Control_Comonad_Env_Class from "../Control.Comonad.Env.Class/index.js";
import * as Control_Comonad_Env_Trans from "../Control.Comonad.Env.Trans/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Identity from "../Data.Identity/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var withEnv = Control_Comonad_Env_Trans.withEnvT;
var runEnv = function (v) {
    return Data_Functor.map(Data_Tuple.functorTuple)(unwrap)(v);
};
var mapEnv = /* #__PURE__ */ Data_Functor.map(/* #__PURE__ */ Control_Comonad_Env_Trans.functorEnvT(Data_Identity.functorIdentity));
var env = function (e) {
    return function (a) {
        return Data_Function.apply(Control_Comonad_Env_Trans.EnvT)(Data_Function.apply(Data_Tuple.Tuple.create(e))(a));
    };
};
export {
    runEnv,
    withEnv,
    mapEnv,
    env
};
export {
    ask,
    asks,
    local
} from "../Control.Comonad.Env.Class/index.js";
export {
    EnvT,
    mapEnvT,
    runEnvT,
    withEnvT
} from "../Control.Comonad.Env.Trans/index.js";
//# sourceMappingURL=index.js.map
