// Generated by purs version 0.15.16
import * as Control_Comonad from "../Control.Comonad/index.js";
import * as Control_Extend from "../Control.Extend/index.js";
import * as Data_Function from "../Data.Function/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Monoid from "../Data.Monoid/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
var TracedT = function (x) {
    return x;
};
var runTracedT = function (v) {
    return v;
};
var newtypeTracedT = {
    Coercible0: function () {
        return undefined;
    }
};
var functorTracedT = function (dictFunctor) {
    return {
        map: function (f) {
            return function (v) {
                return Data_Functor.map(dictFunctor)(function (g) {
                    return function (t) {
                        return Data_Function.apply(f)(g(t));
                    };
                })(v);
            };
        }
    };
};
var extendTracedT = function (dictExtend) {
    var Functor0 = dictExtend.Functor0();
    var functorTracedT1 = functorTracedT(dictExtend.Functor0());
    return function (dictSemigroup) {
        return {
            extend: function (f) {
                return function (v) {
                    return Control_Extend.extend(dictExtend)(function (w$prime) {
                        return function (t) {
                            return Data_Function.apply(f)(Data_Functor.map(Functor0)(function (h) {
                                return function (t$prime) {
                                    return Data_Function.apply(h)(Data_Semigroup.append(dictSemigroup)(t)(t$prime));
                                };
                            })(w$prime));
                        };
                    })(v);
                };
            },
            Functor0: function () {
                return functorTracedT1;
            }
        };
    };
};
var comonadTransTracedT = function (dictMonoid) {
    return {
        lower: function (dictComonad) {
            var Functor0 = (dictComonad.Extend0()).Functor0();
            return function (v) {
                return Data_Functor.map(Functor0)(function (f) {
                    return f(Data_Monoid.mempty(dictMonoid));
                })(v);
            };
        }
    };
};
var comonadTracedT = function (dictComonad) {
    var extendTracedT1 = extendTracedT(dictComonad.Extend0());
    return function (dictMonoid) {
        var extendTracedT2 = extendTracedT1(dictMonoid.Semigroup0());
        return {
            extract: function (v) {
                return Control_Comonad.extract(dictComonad)(v)(Data_Monoid.mempty(dictMonoid));
            },
            Extend0: function () {
                return extendTracedT2;
            }
        };
    };
};
export {
    TracedT,
    runTracedT,
    newtypeTracedT,
    functorTracedT,
    extendTracedT,
    comonadTracedT,
    comonadTransTracedT
};
//# sourceMappingURL=index.js.map
