// Generated by purs version 0.15.16
import * as Control_Monad_Cont_Class from "../Control.Monad.Cont.Class/index.js";
import * as Control_Monad_Cont_Trans from "../Control.Monad.Cont.Trans/index.js";
import * as Control_Semigroupoid from "../Control.Semigroupoid/index.js";
import * as Data_Identity from "../Data.Identity/index.js";
import * as Data_Newtype from "../Data.Newtype/index.js";
var unwrap = /* #__PURE__ */ Data_Newtype.unwrap();
var unwrap1 = /* #__PURE__ */ Data_Newtype.unwrap();
var unwrap2 = /* #__PURE__ */ Data_Newtype.unwrap();
var withCont = function (f) {
    return Control_Monad_Cont_Trans.withContT((function () {
        var $3 = Control_Semigroupoid.compose(Control_Semigroupoid.semigroupoidFn)(Data_Identity.Identity);
        var $4 = Control_Semigroupoid.compose(Control_Semigroupoid.semigroupoidFn)(unwrap);
        return function ($5) {
            return $3(f($4($5)));
        };
    })());
};
var runCont = function (cc) {
    return function (k) {
        return Data_Newtype.unwrap()(Control_Monad_Cont_Trans.runContT(cc)(function ($6) {
            return Data_Identity.Identity(k($6));
        }));
    };
};
var mapCont = function (f) {
    return Control_Monad_Cont_Trans.mapContT(function ($7) {
        return Data_Identity.Identity(f(unwrap1($7)));
    });
};
var cont = function (f) {
    return function (c) {
        return f(function ($8) {
            return unwrap2(c($8));
        });
    };
};
export {
    cont,
    runCont,
    mapCont,
    withCont
};
export {
    callCC
} from "../Control.Monad.Cont.Class/index.js";
export {
    ContT,
    lift,
    mapContT,
    runContT,
    withContT
} from "../Control.Monad.Cont.Trans/index.js";
//# sourceMappingURL=index.js.map
