import fs from 'fs';
import path from 'path';

export const mergeComposersImpl = function({ outputDir, packageRoots }) {
    return function() {
        const rootDir = process.cwd();
        
        let requireDeps = {};
        let requireDevDeps = {};
        
        const outDir = path.resolve(rootDir, outputDir);

        // Roots are resolved and deduplicated before emission. Later manifests
        // still overwrite earlier requirements, including require-dev.
        for (const dir of packageRoots) {
            const compPath = path.join(dir, 'composer.json');
            if (fs.existsSync(compPath)) {
                try {
                    const comp = JSON.parse(fs.readFileSync(compPath, 'utf8'));
                    if (comp.require) {
                        for (const pkg of Object.keys(comp.require)) {
                            requireDeps[pkg] = comp.require[pkg];
                        }
                    }
                    if (comp['require-dev']) {
                        for (const pkg of Object.keys(comp['require-dev'])) {
                            requireDevDeps[pkg] = comp['require-dev'][pkg];
                        }
                    }
                } catch (e) {
                    // ignore
                }
            }
        }
        
        const outPkg = {
            "name": "phpurs/lib-deps",
            "description": "Auto-generated by phpurs",
            "require": requireDeps,
            "require-dev": requireDevDeps
        };
        
        const outPath = path.join(outDir, 'composer.json');
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true });
        }
        fs.writeFileSync(outPath, JSON.stringify(outPkg, null, 4));
    };
};

// End of ComposerMerge
