import fs from 'fs';
import path from 'path';

function getScanDirs(mbFfiDir) {
    const rootDir = process.cwd();
    const scanDirs = [];
    
    const spagoDirs = [
        path.join(rootDir, '.spago'),
        path.join(rootDir, 'spago.d'),
        path.join(rootDir, 'bak/spago.d/php/p')
    ];
    
    for (const spagoDir of spagoDirs) {
        if (fs.existsSync(spagoDir) && fs.statSync(spagoDir).isDirectory()) {
            const packages = fs.readdirSync(spagoDir);
            for (const pkg of packages) {
                const pkgDir = path.join(spagoDir, pkg);
                if (fs.statSync(pkgDir).isDirectory()) {
                    let hasVersion = false;
                    const subdirs = fs.readdirSync(pkgDir);
                    for (const subdir of subdirs) {
                        const versionDir = path.join(pkgDir, subdir);
                        if (subdir.startsWith('v') && fs.statSync(versionDir).isDirectory()) {
                            scanDirs.push(versionDir);
                            hasVersion = true;
                        }
                    }
                    if (!hasVersion) {
                        scanDirs.push(pkgDir);
                    }
                }
            }
        }
    }
    
    if (mbFfiDir) {
        scanDirs.push(path.join(rootDir, mbFfiDir));
    }
    
    return scanDirs;
}

export const mergeComposersImpl = function(mbFfiDir) {
    return function() {
        const rootDir = process.cwd();
        
        let requireDeps = {};
        let requireDevDeps = {};
        
        const scanDirsSet = new Set(getScanDirs(mbFfiDir));
        const outDir = path.join(rootDir, 'output');
        if (fs.existsSync(outDir)) {
            const mods = fs.readdirSync(outDir);
            for (const m of mods) {
                const corefnPath = path.join(outDir, m, 'corefn.json');
                if (fs.existsSync(corefnPath)) {
                    try {
                        const corefn = JSON.parse(fs.readFileSync(corefnPath, 'utf8'));
                        if (corefn.modulePath) {
                            const match = corefn.modulePath.match(/^(.*?)\/(?:src|test)\//);
                            if (match) {
                                scanDirsSet.add(path.resolve(rootDir, match[1]));
                            } else {
                                // Fallback if no src/ or test/ directory
                                scanDirsSet.add(path.resolve(rootDir, path.dirname(corefn.modulePath)));
                            }
                        }
                    } catch (e) {}
                }
            }
        }
        
        for (const dir of scanDirsSet) {
            const compPath = path.join(dir, 'composer.json');
            if (fs.existsSync(compPath)) {
                try {
                    const comp = JSON.parse(fs.readFileSync(compPath, 'utf8'));
                    if (comp.require) {
                        for (const pkg of Object.keys(comp.require)) {
                            requireDeps[pkg] = comp.require[pkg];
                        }
                    }
                    if (comp['require-dev']) {
                        for (const pkg of Object.keys(comp['require-dev'])) {
                            requireDevDeps[pkg] = comp['require-dev'][pkg];
                        }
                    }
                } catch (e) {
                    // ignore
                }
            }
        }
        
        const outPkg = {
            "name": "phpurs/ffi-dependencies",
            "description": "Auto-generated by phpurs",
            "require": requireDeps,
            "require-dev": requireDevDeps
        };
        
        const outPath = path.join(outDir, 'composer.json');
        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, { recursive: true });
        }
        fs.writeFileSync(outPath, JSON.stringify(outPkg, null, 4));
        
        console.log(`phpurs: Generated ${path.relative(rootDir, outPath)} with FFI dependencies.`);
    };
};

export const findFfiFileImpl = function(mbFfiDir) {
    return function(modNameStr) {
        return function(mbModulePath) {
            return function() {
                if (mbModulePath) {
                    const phpPath = mbModulePath.replace(/\.purs$/, '.php');
                    if (fs.existsSync(phpPath)) {
                        return phpPath;
                    }
                }
                
                const scanDirs = getScanDirs(mbFfiDir);
                for (const dir of scanDirs) {
                    // Search in dir/src and dir/
                    const searchPaths = [
                        path.join(dir, 'src', ...modNameStr.split('.')) + '.php',
                        path.join(dir, 'src', modNameStr + '.php'),
                        path.join(dir, modNameStr + '.php')
                    ];
                    for (const p of searchPaths) {
                        if (fs.existsSync(p)) {
                            return p;
                        }
                    }
                }
                return null;
            };
        };
    };
};

