// Generated by purs version 0.15.16
var foo = function (s) {
    return s;
};
var baz = function (s) {
    return function (v) {
        return s;
    };
};
export {
    foo,
    baz
};
//# sourceMappingURL=index.js.map
